server:
  port: :8080
  read_timeout: 10s
  write_timeout: 10s
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: Aa1234
  dbname: userdb
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 5
  max_life_time: 30
logger:
  level: -4 # -4, 0, 4, 8
  format: json # json, text
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
jwt:
  access_ttl: "15m"

